'use strict';

goog.provide('Blockly.Blocks.rgbled');

goog.require('Blockly.Blocks');




Blockly.Blocks.rgbled={};Blockly.Blocks.rgbled.HUE=215;Blockly.Blocks.rgbled.image=filepath.media+"/rgbled.jpg";Blockly.Blocks.rgbled.checkBlocks=function(a){var b=null,d=a.type;a=a.workspace.getAllBlocks();for(var c=0;c<a.length;c++)if("rgbled_setpixelcolor"!=a[c].type&&"rgbled_custom_setpixelcolor"!=a[c].type&&"rgbled_show"!=a[c].type&&"rgbled_setpixelcolor2"!=a[c].type||null!=b||(b=a[c].type!=d?!0:!1),"rgbled_begin"==a[c].type)return!0;return b};
Blockly.Blocks.rgbled_begin={init:function(){this.setHelpUrl(Blockly.Msg.RGBLED_BEGIN_HELPURL);this.setColour(Blockly.Blocks.rgbled.HUE);this.appendDummyInput().appendField(new Blockly.FieldImage(Blockly.Blocks.rgbled.image,64,64)).appendField(Blockly.Msg.RGBLED_BEGIN_SETTING).appendField(Blockly.Msg.RGBLED_BEGIN_NUM).appendField(new Blockly.FieldTextInput("16"),"NUM");this.appendDummyInput().appendField(Blockly.Msg.RGBLED_BEGIN_PIN).appendField(new Blockly.FieldDropdown(profile["default"].digital),
"PIN");this.appendDummyInput().appendField(Blockly.Msg.RGBLED_BEGIN_BRIGHTNESS).appendField(new Blockly.FieldTextInput("50"),"BRIGHTNESS");this.setInputsInline(!0);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.RGBLED_BEGIN_TOOLTIP)},onchange:function(){this.workspace&&this.setWarningText(Blockly.Msg.RGBLED_BEGIN_WARNING)}};
Blockly.Blocks.rgbled_setpixelcolor={init:function(){this.setHelpUrl(Blockly.Msg.RGBLED_SETPIXELCOLOR_HELPURL);this.setColour(Blockly.Blocks.rgbled.HUE);this.appendDummyInput().appendField(new Blockly.FieldImage(Blockly.Blocks.rgbled.image,64,64)).appendField(Blockly.Msg.RGBLED_SETPIXELCOLOR_TARGET).appendField(new Blockly.FieldTextInput("0"),"TARGET");this.appendDummyInput().setAlign(Blockly.ALIGN_RIGHT).appendField(Blockly.Msg.COLOR).appendField(new Blockly.FieldColour("#00ff00"),"RGB");this.setInputsInline(!0);
this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.RGBLED_SETPIXELCOLOR_TOOLTIP)},onchange:function(){this.workspace&&(Blockly.Blocks.rgbled.checkBlocks(this)?this.setWarningText(null):this.setWarningText(Blockly.Msg.RGBLED_WARNING))}};
Blockly.Blocks.rgbled_setpixelcolor2={init:function(){this.setHelpUrl(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_HELPURL);this.setColour(Blockly.Blocks.rgbled.HUE);this.appendDummyInput().appendField(new Blockly.FieldImage(Blockly.Blocks.rgbled.image,64,64));this.appendValueInput("TARGET").setCheck("Number").appendField(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_TARGET);this.appendDummyInput().setAlign(Blockly.ALIGN_RIGHT).appendField(Blockly.Msg.COLOR).appendField(new Blockly.FieldColour("#00ff00"),"RGB");
this.setInputsInline(!0);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_TOOLTIP)},onchange:function(){this.workspace&&(Blockly.Blocks.rgbled.checkBlocks(this)?this.setWarningText(null):this.setWarningText(Blockly.Msg.RGBLED_WARNING))}};
Blockly.Blocks.rgbled_custom_setpixelcolor={init:function(){this.setHelpUrl(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_HELPURL);this.setColour(Blockly.Blocks.rgbled.HUE);this.appendDummyInput().appendField(new Blockly.FieldImage(Blockly.Blocks.rgbled.image,64,64));this.appendValueInput("TARGET").setCheck("Number").appendField(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_TARGET);this.appendValueInput("R").setCheck("Number").appendField(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_R);this.appendValueInput("G").setCheck("Number").appendField(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_G);
this.appendValueInput("B").setCheck("Number").appendField(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_B);this.setInputsInline(!0);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.RGBLED_CUSTOM_SETPIXELCOLOR_TOOLTIP)},onchange:function(){this.workspace&&(Blockly.Blocks.rgbled.checkBlocks(this)?this.setWarningText(null):this.setWarningText(Blockly.Msg.RGBLED_WARNING))}};
Blockly.Blocks.rgbled_show={init:function(){this.setHelpUrl(Blockly.Msg.RGBLED_SHOW_HELPURL);this.setColour(Blockly.Blocks.rgbled.HUE);this.appendDummyInput().appendField(new Blockly.FieldImage(Blockly.Blocks.rgbled.image,64,64)).appendField(Blockly.Msg.RGBLED_SHOW);this.setInputsInline(!0);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.RGBLED_SHOW_TOOLTIP)},onchange:function(){this.workspace&&(Blockly.Blocks.rgbled.checkBlocks(this)?this.setWarningText(null):
this.setWarningText(Blockly.Msg.RGBLED_WARNING))}}
